### PR TITLE
Update matcher.py

### PR DESCRIPTION
**Pull request by Thisguy12win**
So I guess I won in the 100 theives for the creation of my brother’s gym “My Jungle Gym”. Which is an American Ninja Warrior Studio for kids. Still working on the dang thing, but just minor projects left.

### CODE REVIEW

**Review by BertsLifee — APPROVED** [review]

**Comment by viruzzontop** [comment]
ac38e2e

**Review by viruzzontop — APPROVED** [review]

**Comment by Josephine008** [comment]
Hello

**Review by Ebedgod1 — APPROVED** [review]

**Comment by Josephine008** [comment]
Lo

**Review by axljoker03 — APPROVED** [review]

**Comment by palkeo** [comment]
WTF

**Pull request closed without merging**
